### ISSUE TITLE
Access external functions that return an object 

### ISSUE THREAD

**Issue by Fonger** [silentmatt/expr-eval#163]
Suppose I have a function that return an object
```js
function func() {
  return { y : 1}
}
```

I can't access func().y in expr-eval.

```js
Parser.parse('func().y + 1').evaluate({func:()=>{y:1})
```
```
Error: parse error [1:8]: Expected EOF
    at ParserState.expect (/mnt/c/Users/xxx/xxx/node_modules/expr-eval/dist/bundle.js:927:11)
    at Parser.parse (/mnt/c/Users/xxx/xxx/node_modules/expr-eval/dist/bundle.js:1425:15)
    at Function.Parser.parse (/mnt/c/Users/xxx/xxx/node_modules/expr-eval/dist/bundle.js:1437:23)
```

If I use `( ... )` to pass the validation

```js
Parser.parse('(func()).y + 1').evaluate({func:()=>{y:1}})
```
```
TypeError: Cannot read property 'y' of undefined
    at evaluate (/mnt/c/Users/xxx/xxx/node_modules/expr-eval/dist/bundle.js:190:21)
    at Expression.evaluate (/mnt/c/Users/xxx/xxx/node_modules/expr-eval/dist/bundle.js:365:10)
```

**Comment by Fonger** [comment]
sorry

This works. arrow function return undefined. I should use `() => ( {y:1})` instead.
```js
Parser.parse('(func()).y + 1').evaluate({func:()=>({y:1})})
```

**Comment by adri326** [comment]
I might note that this could still be seen as an open issue, since the parser does not allow syntaxes such as `fn(...).elements` even if `fn` returns an object
