### ISSUE TITLE
Cannot uglify with latest version

### ISSUE THREAD

**Issue by juggy** [silentmatt/expr-eval#53]
```
➜  front-end git:(staging-schedule) ✗ ./node_modules/.bin/uglifyjs bower_components/js-expression-eval/parser.js 
Parse error at bower_components/js-expression-eval/parser.js:1169,7
SyntaxError: Unexpected token: keyword (default)
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/juggy/Documents/porkepic/vroom/front-end/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)
    at js_error (eval at <anonymous> (/Users/juggy/Documents/porkepic/vroom/front-end/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)
    at croak (eval at <anonymous> (/Users/juggy/Documents/porkepic/vroom/front-end/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2092:9)
    at token_error (eval at <anonymous> (/Users/juggy/Documents/porkepic/vroom/front-end/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2100:9)
    at unexpected (eval at <anonymous> (/Users/juggy/Documents/porkepic/vroom/front-end/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2106:9)
    at semicolon (eval at <anonymous> (/Users/juggy/Documents/porkepic/vroom/front-end/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2126:56)
    at simple_statement (eval at <anonymous> (/Users/juggy/Documents/porkepic/vroom/front-end/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2317:73)
    at eval (eval at <anonymous> (/Users/juggy/Documents/porkepic/vroom/front-end/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2186:19)
    at eval (eval at <anonymous> (/Users/juggy/Documents/porkepic/vroom/front-end/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2139:24)
    at eval (eval at <anonymous> (/Users/juggy/Documents/porkepic/vroom/front-end/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2907:23)
```

**Comment by juggy** [comment]
Arg - I see you converted it to a module using npm - so nevermind.

**Comment by silentmatt** [comment]
For posterity's sake, in case anyone else comes across this, the file you want to use (and uglify) is `./dist/bundle.js`. If you install through npm, it will be there already, or if you're cloning/downloading the git repository, run `npm install` to install the build dependencies and generate the bundle.js file. `parser.js` is an ES6 module, so it won't currently work without being converted to a CommonJS/AMD module first.
